-- ==========================================================
-- 1. STRUCTURE DE LA BASE DE DONNÉES (MODE ULTRA ROBUSTE)
-- ==========================================================

-- Table des Produits
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Vape',
  price TEXT NOT NULL,
  old_price TEXT,
  image_url TEXT,
  description TEXT,
  badge TEXT,
  badge_color TEXT DEFAULT 'bg-neon-red',
  glow_color TEXT DEFAULT 'box-glow-green-hover',
  flavors JSONB DEFAULT '[]'::jsonb,
  stock_quantity INTEGER DEFAULT 0,
  is_visible BOOLEAN DEFAULT TRUE,
  is_18_plus BOOLEAN DEFAULT FALSE,
  views_count BIGINT DEFAULT 0,
  images JSONB DEFAULT '[]'::jsonb,
  video_url TEXT
);

-- Forcer l'ajout des colonnes au cas où la table existe déjà sans elles
ALTER TABLE products ADD COLUMN IF NOT EXISTS old_price TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS badge TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS badge_color TEXT DEFAULT 'bg-neon-red';
ALTER TABLE products ADD COLUMN IF NOT EXISTS glow_color TEXT DEFAULT 'box-glow-green-hover';
ALTER TABLE products ADD COLUMN IF NOT EXISTS flavors JSONB DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_visible BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_18_plus BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS views_count BIGINT DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS video_url TEXT;

-- Table des Commandes
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_wilaya TEXT NOT NULL,
  customer_address TEXT,
  items_list TEXT NOT NULL,
  subtotal_price BIGINT DEFAULT 0,
  delivery_price BIGINT DEFAULT 0,
  total_price BIGINT NOT NULL,
  status TEXT DEFAULT 'En attente'
);

-- Forcer la mise à jour de la table orders si elle existe déjà
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_price BIGINT DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_price BIGINT DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS items_list TEXT DEFAULT 'Non spécifié';
ALTER TABLE orders ALTER COLUMN total_price TYPE BIGINT USING total_price::BIGINT;
ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'En attente';

-- Table des Administrateurs
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  passcode TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- 2. SÉCURITÉ ET POLITIQUES (RLS)
-- ==========================================================

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- Politiques Produits
DROP POLICY IF EXISTS "Allow anyone to read products" ON products;
CREATE POLICY "Allow anyone to read products" ON products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow anyone to insert products" ON products;
CREATE POLICY "Allow anyone to insert products" ON products FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow anyone to update products" ON products;
CREATE POLICY "Allow anyone to update products" ON products FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow anyone to delete products" ON products;
CREATE POLICY "Allow anyone to delete products" ON products FOR DELETE USING (true);

-- Politiques Commandes
DROP POLICY IF EXISTS "Allow anyone to insert orders" ON orders;
CREATE POLICY "Allow anyone to insert orders" ON orders FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow anyone to read orders" ON orders;
CREATE POLICY "Allow anyone to read orders" ON orders FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow anyone to update orders" ON orders;
CREATE POLICY "Allow anyone to update orders" ON orders FOR UPDATE USING (true);
DROP POLICY IF EXISTS "Allow anyone to delete orders" ON orders;
CREATE POLICY "Allow anyone to delete orders" ON orders FOR DELETE USING (true);

-- Politiques Admins
DROP POLICY IF EXISTS "Allow anyone to read admins" ON admins;
CREATE POLICY "Allow anyone to read admins" ON admins FOR SELECT USING (true);

-- ==========================================================
-- 3. INITIALISATION ET STOCKAGE
-- ==========================================================

-- Création de l'admin par défaut
INSERT INTO admins (name, passcode) 
VALUES ('Principal Admin', 'ZONE2026')
ON CONFLICT (passcode) DO NOTHING;

-- Configuration du Bucket de stockage pour les images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('products', 'products', true) 
ON CONFLICT (id) DO NOTHING;

-- Politiques de stockage des fichiers
DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING ( bucket_id = 'products' );
DROP POLICY IF EXISTS "Public Insert Access" ON storage.objects;
CREATE POLICY "Public Insert Access" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'products' );
DROP POLICY IF EXISTS "Public Update Access" ON storage.objects;
CREATE POLICY "Public Update Access" ON storage.objects FOR UPDATE USING ( bucket_id = 'products' );
DROP POLICY IF EXISTS "Public Delete Access" ON storage.objects;
CREATE POLICY "Public Delete Access" ON storage.objects FOR DELETE USING ( bucket_id = 'products' );

-- ==========================================================
-- 4. FIN DU SCRIPT
-- ==========================================================
