-- ==========================================
-- 1. TABLE DES PRODUITS (Mise à jour)
-- ==========================================
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Vape',
  price TEXT NOT NULL,
  old_price TEXT,
  image_url TEXT,
  description TEXT,
  badge TEXT,
  badge_color TEXT DEFAULT 'bg-[#ef4444]',
  glow_color TEXT DEFAULT 'box-glow-green-hover',
  flavors JSONB DEFAULT '[]'::jsonb,
  stock_quantity INTEGER DEFAULT 0,
  is_visible BOOLEAN DEFAULT TRUE,
  is_18_plus BOOLEAN DEFAULT FALSE,
  views_count BIGINT DEFAULT 0,
  images JSONB DEFAULT '[]'::jsonb,
  video_url TEXT
);

-- Activation de la sécurité (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ADD COLUMN IF NOT EXISTS images JSONB DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS video_url TEXT;

-- Nettoyage et création des politiques d'accès
DROP POLICY IF EXISTS "Allow anyone to read products" ON products;
DROP POLICY IF EXISTS "Allow anyone to insert products" ON products;
DROP POLICY IF EXISTS "Allow anyone to update products" ON products;
DROP POLICY IF EXISTS "Allow anyone to delete products" ON products;

CREATE POLICY "Allow anyone to read products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow anyone to insert products" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anyone to update products" ON products FOR UPDATE USING (true);
CREATE POLICY "Allow anyone to delete products" ON products FOR DELETE USING (true);


-- ==========================================
-- 2. TABLE DES COMMANDES
-- ==========================================
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_wilaya TEXT NOT NULL,
  customer_address TEXT,
  items_list TEXT NOT NULL,
  subtotal_price BIGINT DEFAULT 0,
  delivery_price BIGINT DEFAULT 0,
  total_price TEXT NOT NULL,
  status TEXT DEFAULT 'En attente'
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anyone to insert orders" ON orders;
DROP POLICY IF EXISTS "Allow anyone to read orders" ON orders;
DROP POLICY IF EXISTS "Allow anyone to update orders" ON orders;
DROP POLICY IF EXISTS "Allow anyone to delete orders" ON orders;

CREATE POLICY "Allow anyone to insert orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anyone to read orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow anyone to update orders" ON orders FOR UPDATE USING (true);
CREATE POLICY "Allow anyone to delete orders" ON orders FOR DELETE USING (true);


-- ==========================================
-- 3. TABLE DE L'ÉQUIPE (Admins)
-- ==========================================
CREATE TABLE IF NOT EXISTS admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  passcode TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anyone to read admins" ON admins;
DROP POLICY IF EXISTS "Allow anyone to insert admins" ON admins;
DROP POLICY IF EXISTS "Allow anyone to update admins" ON admins;
DROP POLICY IF EXISTS "Allow anyone to delete admins" ON admins;

CREATE POLICY "Allow anyone to read admins" ON admins FOR SELECT USING (true);
CREATE POLICY "Allow anyone to insert admins" ON admins FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anyone to update admins" ON admins FOR UPDATE USING (true);
CREATE POLICY "Allow anyone to delete admins" ON admins FOR DELETE USING (true);


-- ==========================================
-- 4. INSERTION DE L'ADMIN PAR DÉFAUT
-- ==========================================
INSERT INTO admins (name, passcode) 
VALUES ('Principal Admin', 'ZONE2026')
ON CONFLICT (passcode) DO NOTHING;


-- ==========================================
-- 5. STOCKAGE DES IMAGES (Bucket Produits)
-- ==========================================
-- Création automatique du bucket si inexistant via l'API interne
INSERT INTO storage.buckets (id, name, public) 
VALUES ('products', 'products', true) 
ON CONFLICT (id) DO NOTHING;

-- Politiques de stockage
DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Access" ON storage.objects;

CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING ( bucket_id = 'products' );
CREATE POLICY "Public Insert Access" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'products' );
CREATE POLICY "Public Update Access" ON storage.objects FOR UPDATE USING ( bucket_id = 'products' );
CREATE POLICY "Public Delete Access" ON storage.objects FOR DELETE USING ( bucket_id = 'products' );
